plugins {
    id "com.android.application" version "9.4.0"
}

android {
    namespace = "com.anland.termux"
    compileSdk = 37
    compileSdkMinor = 2

    buildFeatures {
        buildConfig = true
        aidl = true
    }

    signingConfigs {
        termuxGitHub {
            storeFile = rootProject.file("testkey_untrusted.jks")
            keyAlias = "alias"
            storePassword = "xrj45yWGLbsO7W0v"
            keyPassword = "xrj45yWGLbsO7W0v"
        }
    }

    defaultConfig {
        applicationId = "com.anland.termux"
        minSdk = 30
        targetSdk = 37
        versionCode = 8
        versionName = "5.13.3"

        ndk {
            abiFilters "arm64-v8a"
        }

        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=none"
            }
        }
    }

    flavorDimensions "transport"
    productFlavors {
        standard {
            dimension "transport"
            buildConfigField "boolean", "COMPATIBLE", "false"
        }
        compatible {
            dimension "transport"
            buildConfigField "boolean", "COMPATIBLE", "true"
            versionNameSuffix "-compatible"
        }
    }

    ndkVersion = "29.0.14206865"

    externalNativeBuild {
        cmake {
            path = file("src/main/jni/CMakeLists.txt")
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    buildTypes {
        debug {
            signingConfig = signingConfigs.termuxGitHub
        }
        release {
            signingConfig = signingConfigs.termuxGitHub
            minifyEnabled = false
        }
    }
}
